### ISSUE TITLE
Does not work within CodePipeline

### ISSUE THREAD

**Issue by mbonig** [Defiance-Digital/cdk-git-tagger#11]
This aspect will not currently work when you are using the CodePipeline for doing synthesizing, either directly of via the pipelines/CodePipeline [construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html).

The root cause is because CodePipeline's source actions transfer the code assets to CodeBuild and does not carry the .git metadata directory with it.

If you try to use this construct, it will throw an error during the synth steps:

```
Error: No .git folder found
```

There are a few ways I think this could be handled:

1. Do not throw the error, produce a warning instead. I don't love this because it likely will result in confusion, like "why isn't my stuff tagged" and it won't be immediately clear that you have to go to the CodeBuild logs to see why.
2. Treat the request the same way imports work, and use a local cache (like context, but not cause context isn't easily accessible) to store the value so it's not re-read during CICD builds.

**Comment by mbonig** [comment]
There is a workaround that helps, but is not perfect. Add the option to the input connection object, `codeBuildCloneOutput: true`.

```
    const pipeline = new CodePipeline(this, 'Pipeline', {
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.connection('Defiance-Digital/cdk-aspects-tester', 'main', {
          connectionArn: 'arn:aws:codestar-connections:us-east-1:00001111222:connection/6437fe74-41e3-4ad3-8fb5-fcfb867b66da',
          codeBuildCloneOutput: true,
        }),
        commands: [
          'yarn install --frozen-lockfile',
          'yarn build',
          'npx cdk synth',
        ],
      }),
    });
```

**Comment by dannysteenman** [comment]
Internally we have repo's that use cdk pipelines to synth and deploy stacks via codepipeline. The way we tag all resources on stacks that are deployed via codepipeline stages are done like so:

```
import { Stack, Aspects, TagManager, IResource } from 'aws-cdk-lib';
import { Construct } from 'constructs';

/**
 * Tag all supported resources within an application.
 *
 * CDK will propagate tags too all resources that support it.
 */
export function tagResources(scope: Construct, tags: (stack: Stack) => Record<string, string>): void {
  Aspects.of(scope).add({
    visit(construct: IResource) {
      if (TagManager.isTaggable(construct)) {
        // We pick the last stack in chain to support stages where
        // there are multiple stacks.
        const allStacks = construct.node.scopes.filter((it): it is Stack => Stack.isStack(it));

        const stack = allStacks.length > 0 ? allStacks[allStacks.length - 1] : undefined;
        if (stack != null) {
          for (const [key, value] of Object.entries(tags(stack))) {
            construct.tags.setTag(key, value, 100, true);
          }
        }
      }
    },
  });
}

```

for a new cdk pipeline stage:

```
      // Tags all the resources in the target account
      tagResources(awsAccount, (stack) => ({
        customer: 'customer-name',
        stage: awsAccount.stageName,
      }));
```
